export enum Unit {
  GRAM = "g",
  KILOGRAM = "kg",
  MILLILITER = "ml",
  LITER = "l",
  TEASPOON = "tsp",
  TABLESPOON = "tbsp",
  CUP = "cup",
  PIECE = "piece",
  SLICE = "slice",
  PINCH = "pinch",
  DASH = "dash",
  DROP = "drop",
  BUNCH = "bunch",
  LEAF = "leaf",
  CLOVE = "clove",
  CAN = "can",
  BOTTLE = "bottle",
  PACKAGE = "package"
}
