import swaggerJsdoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';
import { Express } from 'express';
import { settings } from './config/settings';

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Headhunter Competitor API',
      version: '1.0.0',
      description: 'API documentation',
      contact: {
        name: 'Gneushev Vladislav',
        email: 'vladgneushev@gmail.com'
      }
    },
    servers: [
      {
        url: `${settings.app.PROTOCOL}://localhost:${settings.app.PORT}`,
        description: 'Development server'
      }
    ],
  },
  apis: ['./src/routes/**/*.ts', './src/controllers/**/*.ts'],
};

const swaggerSpec = swaggerJsdoc(options);

export const setupSwagger = (app: Express) => {
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
  console.log(`Swagger UI available at /docs, generated by swagger-jsdoc`);
}; 