/**
 * @file Automatically generated by barrelsby.
 */

export * from "./advertisement-service.client";
export * from "./message-service.client";
export * from "./rental-service.client";
export * from "./user-service.client";
